kafka:
  bootstarpServers: "localhost:9092"
  appId: "test2"
  schemaRegistryUrl: "http://localhost:8081"
opentracing:
  zipkin:
    http-sender:
      baseUrl: "http://localhost:9411"

spring:
  application:
    name: kafkaProducer